#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and handles the SIGTERM signal

# Trap SIGTERM (Signal 15) and print a message instead of terminating
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
