#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely and handles the SIGTERM signal

# Define the action to take when SIGTERM (Signal 15) is received
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
